### ISSUE TITLE
Penn State: Thumbnail link fails with https

### ISSUE THREAD

**Issue by dorevabelfiore-temple** [tulibraries/dplah#91] opened 2016-05-31 17:59 UTC
Linda Ballinger reports from Penn State that they were forced to convert their CONTENTdm instance to https. She has deleted and reharvested her collections in the test aggregator. All of the metadata works except the thumbnails. 

Example: http://libcollab.temple.edu/aggregator-testing/catalog/dplapa:PSU_maps1_6990 
Identifier #2:
https://collection1.libraries.psu.edu:9443/oai.php/utils/getthumbnail/collection/maps1/id/6990

the https URL in Identifier gets this error message:

Fatal error: Uncaught exception 'ErrorException' with message 'include(../../../../../../dmscripts/DMUtil.php): failed to open stream: No such file or directory' in /opt/Content6/Server/docs/dmscripts/DMSystem.php:10 Stack trace: #0 /opt/Content6/Server/docs/dmscripts/DMSystem.php(10): exceptions_error_handler(2, 'include(../../....', '/opt/Content6/S...', 10, Array) #1 /opt/Content6/Server/docs/dmscripts/DMSystem.php(10): include() #2 /opt/Content6/Server/docs/oai.php(26): require_once('/opt/Content6/S...') #3 {main} thrown in /opt/Content6/Server/docs/dmscripts/DMSystem.php on line 10

All the other links to the original (image, "View Object", and http link in Identifier work fine.

Is there anything that we can do on our end? The PSU team is investigating with their IT but this will impact the inclusion of additional collections from them.

**Comment by kelynch** [comment] 2016-05-31 18:26
Did some quick testing -- it looks like the thumbnail URL pattern changed a bit with the https change, and possibly on the CONTENTdm software.  I'll put up a pull request tonight if the timing works (if not, please feel free to un-assign me and assign to whoever else).

**Comment by dorevabelfiore-temple** [comment] 2016-05-31 18:51
OK thanks. Would this be a labeled choice like 'CONTENTdm SSL' on the picklist? I can't imagine that many sites would implement HTTPS on their CONTENTdm, but who knows? [My understanding is that OCLC is encouraging everyone to move to hosted services, but yet not sunsetting support for self-hosted instances.]

**Comment by kelynch** [comment] 2016-06-01 01:56
It looks like there may be something odd with their configuration going on that's causing the issue, particularly the port number.  I tried harvesting without the port number (as the thumbnail path that resolves does not include that) and the harvest fails due to an invalid resumption token, but the code receives the same resumption token whether the port number is there or not:

maps1:744:maps1:0000-00-00:9999-99-99:oai_qdc

I tested with and without the port number and the resumption token error only happens when the port number is removed, and again, this is against the exact same resumption token.  I can add a pattern generator for this to the picklist as "CONTENTdm Self-Hosted SSL," which would allow us to resolve the thumbnails and to harvest with the port number attached to the endpoint URL, but given that this error may be being caused by a configuration issue on the server and may therefore not be the norm for CONTENTdm on HTTPS, this might come back to bite us.  That being said, if we don't see many other CONTENTdm seeds needing to be specified as anything other than CONTENTdm standard, this may be all right, and just something to be mindful of eventually moving away from if/when a configuration error is identified and the HTTPS-resolving CONTENTdm instances use the same patterns for thumbnail generation.

**Comment by dorevabelfiore-temple** [comment] 2016-06-01 12:22
Thanks Kate. I wrote to PSU with your test results and said we would hold on this fix until we hear more from them about this problem.

**Comment by EliseTemple** [comment] 2016-06-07 15:30
From Penn State (6/1/2016): 

> At this record:  http://libcollab.temple.edu/aggregator-testing/catalog/dplapa:PSU_benson_152
> there are two links to Identifiers. The first goes to our CONTENTdm content and the second goes to the CONTENTdm thumbnail. The link to our content works, but the link to the thumbnail does not.
> 
> Eric Treece (who is cc'd on this thread) and I looked at this today and found that if the URL to the thumbnail is changed slightly, the thumbnail is found. We are wondering how this link is generated and if it is possible to change the link? By moving our collection to https, it appears that this link needs to be generated differently.
> 
> Link to thumbnail as it is now:
> https://collection1.libraries.psu.edu:9443/oai.php/utils/getthumbnail/collection/benson/id/152
> 
> Correct link to thumbnail:
> https://collection1.libraries.psu.edu/utils/getthumbnail/collection/benson/id/152

**Comment by EliseTemple** [comment] 2016-06-07 15:31
From Linda Ballinger @ Penn State (6/7/2016)

> I haven't heard any follow-up to Todd and Eric's potential thumbnail solution below, so am checking in. Is this something I can try by editing the seed? The Thumbnail Retrieval Details section has a Thumbnail Pattern field, but I can't tell whether I can use the getthumbnail URL below in that field.

**Comment by bibliotechy** [comment] 2016-06-07 17:55
So, contentDM is split into two servers. The backend server that holds the data, where staff tools are located, and where the OAI serving application lives,  and the front end server that presents the UI for the public. 
For hosted ContentDMs they provide a proxy of the backend server on the front end server. So `http://digital.library.temple.edu/oai/oai.php` and `https://server16002.contentdm.oclc.org/oai.php` are providing the same url endpoint.

It looks like in Penn State's case, `http://collection1.libraries.psu.edu/oai/oai.php` doesn't proxy the backend, but redirects to it at `https://collection1.libraries.psu.edu:9443/oai.php`. That should explain the broken resumption tokens when using the portless url. 

So, if Penn State proxies ``https://collection1.libraries.psu.edu:9443/` at `http://digital.library.temple.edu/oai/` this problem would be solved. It would follow other ContentDM setups.

Alternatively, we could alter the thumnail driver as Kate mentioned, stripping out the port and oai string - but this would be Penn State specific as it is a quirk of the way they have their infrastucture set up.

**Comment by kelynch** [comment] 2016-06-07 18:57
Thanks Chad — this is exactly the issue I was referring to in my initial comment. A driver can strip these out without hardcoding if we assume this is how all CONTENTdm SSL clients would work as opposed to a quirk in the infrastructure of the client in question.

**Comment by EliseTemple** [comment] 2016-06-07 19:02
Perhaps this did not come through to the Penn State people, as it seems
they are still looking for us to adjust it on our end.

Maybe instead of laying out all the options we can just ask them if they
can proxy `https://collection1.libraries.psu.edu:9443/ at
http://digital.library.temple.edu/oai/.

If the answer is no, then we can begin to explore a custom fix for them.

Kate - since you were talking to their developers, would you
feel comfortable continuing this, or would you prefer I write to them?




On Tue, Jun 7, 2016 at 2:57 PM, Katherine Lynch <notifications@github.com>
wrote:

> Thanks Chad — this is exactly the issue I was referring to in my initial
> comment. A driver can strip these out without hardcoding if we assume this
> is how all CONTENTdm SSL clients would work as opposed to a quirk in the
> infrastructure of the client in question.
>
> From: Chad Nelson <notifications@github.com<mailto:
> notifications@github.com>>
> Reply-To: tulibraries/dplah <reply@reply.github.com<mailto:
> reply@reply.github.com>>
> Date: Tuesday, June 7, 2016 at 1:55 PM
> To: tulibraries/dplah <dplah@noreply.github.com<mailto:
> dplah@noreply.github.com>>
> Cc: Katherine Lynch <katherly@upenn.edu<mailto:katherly@upenn.edu>>,
> Assign <assign@noreply.github.com<mailto:assign@noreply.github.com>>
> Subject: Re: [tulibraries/dplah] Penn State: Thumbnail link fails with
> https (#91)
>
>
> So, contentDM is split into two servers. The backend server that holds the
> data, where staff tools are located, and where the OAI serving application
> lives, and the front end server that presents the UI for the public.
> For hosted ContentDMs they provide a proxy of the backend server on the
> front end server. So http://digital.library.temple.edu/oai/oai.php and
> https://server16002.contentdm.oclc.org/oai.php are providing the same url
> endpoint.
>
> It looks like in Penn State's case,
> http://collection1.libraries.psu.edu/oai/oai.php doesn't proxy the
> backend, but redirects to it at
> https://collection1.libraries.psu.edu:9443/oai.php. That should explain
> the broken resumption tokens when using the portless url.
>
> So, if Penn State proxies `https://collection1.libraries.psu.edu:9443/ at
> http://digital.library.temple.edu/oai/ this problem would be solved. It
> would follow other ContentDM setups.
>
> Alternatively, we could alter the thumnail driver as Kate mentioned,
> stripping out the port and oai string - but this would be Penn State
> specific as it is a quirk of the way they have their infrastucture set up.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub<
> https://github.com/tulibraries/dplah/issues/91#issuecomment-224361606>,
> or mute the thread<
> https://github.com/notifications/unsubscribe/AHb0VfE_UPEjK_7zIkRuWJ-_pUqDKc6rks5qJbCkgaJpZM4Iqy4W>.
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tulibraries/dplah/issues/91#issuecomment-224379944>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQIsiIV2VQXB3IT3EwrI6CkZ9O1LmYEXks5qJb8pgaJpZM4Iqy4W>
> .
>



-- 


*Elise Warshavsky*Digital Projects and Services Librarian
Digital Library Initiatives
Temple University
elise@temple.edu
215-204-6491

**Comment by kelynch** [comment] 2016-06-07 19:07
I can communicate this to them.  I’ll do so ASAP today.

**Comment by EliseTemple** [comment] 2016-06-08 13:19
Thank you Kate, this is much appreciated.

I think that there was confusion because they had the wrong email address for you. I have asked them to always include Doreva or I on any communication with Developers so we can help with the coordination (in this case point out that they should have emailed you at a different email address)

**Comment by bibliotechy** [comment] 2016-06-08 13:21
I think my point was that if they proxy instead of redirect, we can just use the existing ContentDM driver and then we don't have to write a new driver at all. :smile:

**Comment by kelynch** [comment] 2016-06-08 13:38
Indeed, that's my understanding too, and hesitation to implement the driver.  It's trickiness to work around a quirk, not a standard practice for the OAI client. If they proxy, problem solved, and this is a more standard way of implementing CONTENTdm under SSL.  

I'll update here when I hear back from the developers today.

**Comment by kelynch** [comment] 2016-06-09 19:42
I got in touch with Penn State today and just had a chat with Chad about how to proceed.

Evidently, OCLC at least right now, is advising customers, when moving to SSL, to use a redirect, not proxying, hence the exposure of the port.  Since OCLC is telling customers to do this, it's likely that, if we see another CONTENTdm content provider with SSL (which we acknowledge may be rare), they will likely have the same configuration.  

Given this, we think the way to proceed is to have a driver as we initially discussed, and label it "CONTENTdm SSL (Redirect Method)" in the picklist.  This way, in the even that we encounter later SSL-based CONTENTdm clients, we may proceed with caution in their harvesting and, if they fail, investigate if they're redirecting or proxying.  

Does this sound amenable to all?  If so, I can have a PR up tonight or tomorrow with this.

**Comment by bibliotechy** [comment] 2016-06-09 19:43
:+1:

**Comment by dorevabelfiore-temple** [comment] 2016-06-09 20:22
👍👍

**Comment by EliseTemple** [comment] 2016-06-09 20:41
+1

Thank you Kate, Thank you All..



On Thu, Jun 9, 2016 at 4:22 PM, Doreva Belfiore <notifications@github.com>
wrote:

> 👍👍
>
> Sent from my iPhone
>
> > On Jun 9, 2016, at 3:43 PM, Chad Nelson <notifications@github.com>
> wrote:
> >
> > 👍
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tulibraries/dplah/issues/91#issuecomment-225014717>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQIsiBCf8Wy39Azkp4xVn-NEdz9ovBwPks5qKHYLgaJpZM4Iqy4W>
> .
>



-- 


*Elise Warshavsky*Digital Projects and Services Librarian
Digital Library Initiatives
Temple University
elise@temple.edu
215-204-6491

**Comment by EliseTemple** [comment] 2016-06-13 13:51
Any development on this?  

Gretchen is on vacation today, so we don't think that we will be harvested until tomorrow.  There is a chance to re-harvest Penn State's content w/ thumbnails before DPLA harvests us.

**Comment by kelynch** [comment] 2016-06-13 20:47
My personal laptop's dev environment got nuked on Sunday.  I've been trying to rebuild and will hopefully have it fixed tonight to the point where I can develop/deploy -- given the tight timeline, I won't be offended if someone else wants to grab this issue, however I'll likely be able to submit a PR for early AM tomorrow if that works.  I realize that may well not work for the live harvesting tomorrow, but I'm afraid it's the best I can do. 😞

**Comment by dorevabelfiore-temple** [comment] 2016-06-13 20:49
It's OK. We already told DPLA to hold off harvesting until we tell them and
they are fine with it.

Sorry to hear about your laptop. :-(

--Doreva

On Mon, Jun 13, 2016 at 4:47 PM, Katherine Lynch <notifications@github.com>
wrote:

> My personal laptop's dev environment got nuked on Sunday. I've been trying
> to rebuild and will hopefully have it fixed tonight to the point where I
> can develop/deploy -- given the tight timeline, I won't be offended if
> someone else wants to grab this issue, however I'll likely be able to
> submit a PR for early AM tomorrow if that works. I realize that may well
> not work for the live harvesting tomorrow, but I'm afraid it's the best I
> can do. 😞
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tulibraries/dplah/issues/91#issuecomment-225703448>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQOsq4bF5FJgrSNGzU9f_benJ_fG4Fajks5qLcHagaJpZM4Iqy4W>
> .
>



-- 
Doreva Belfiore

Digital Projects Librarian
Digital Library Initiatives
Temple University Libraries
215-204-4942 (P)
215-204-3681 (F)

**Comment by kelynch** [comment] 2016-06-13 20:54
Thanks!  I'll keep you posted and submit a PR ASAP.

**Comment by kelynch** [comment] 2016-06-14 00:39
Addressed by #105

**Closed** 2016-06-14 15:03 UTC
Labels: harvesting, metadata, priority high, waffle: Needs QA
